name: "Product Flow – Fließend zum Erfolg"
description: "Der Podcast über erfolgreiche Produktentwicklung, Selbstorganisation und fokussierte Beta-Teams"
meta_description: "Product Flow – Fließend zum Erfolg. Der Podcast über erfolgreiche Produktentwicklung, Selbstorganisation und fokussierte Beta-Teams von Patrick Koglin, David Orlowski und Thorben Egberts."

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://www.productflow-podcast.de'
google_analytics: 'UA-XXXXXXXX-X'
gems:
  - jekyll-paginate

# Details for the RSS feed generator
url:            'https://www.productflow-podcast.de'
author:         'Patrick Koglin, David Orlowski, Thorben Egberts'
